ALTER TABLE kutir_visits
  ADD COLUMN IF NOT EXISTS kutir_closed BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS plan_hindi   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS plan_math    BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS plan_english BOOLEAN NOT NULL DEFAULT FALSE;
