ALTER TABLE users
  ADD COLUMN IF NOT EXISTS district_id INTEGER REFERENCES districts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS cluster_id  INTEGER REFERENCES clusters(id)  ON DELETE SET NULL;
